export const CLASSIFICATION_CONFIG = {
  recommended: {
    label: 'Recommended',
    color: 'text-green-700',
    bg: 'bg-green-50',
    border: 'border-green-200',
    icon: '✓',
    dotColor: 'bg-green-500',
  },
  recommended_in_moderation: {
    label: 'In Moderation',
    color: 'text-emerald-700',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    icon: '◑',
    dotColor: 'bg-emerald-400',
  },
  neutral: {
    label: 'Neutral',
    color: 'text-slate-600',
    bg: 'bg-slate-50',
    border: 'border-slate-200',
    icon: '—',
    dotColor: 'bg-slate-400',
  },
  limit: {
    label: 'Limit',
    color: 'text-amber-700',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    icon: '!',
    dotColor: 'bg-amber-400',
  },
  use_cautiously: {
    label: 'Use Caution',
    color: 'text-orange-700',
    bg: 'bg-orange-50',
    border: 'border-orange-200',
    icon: '⚠',
    dotColor: 'bg-orange-500',
  },
  avoid: {
    label: 'Avoid',
    color: 'text-red-700',
    bg: 'bg-red-50',
    border: 'border-red-200',
    icon: '✕',
    dotColor: 'bg-red-500',
  },
  blocked_allergy: {
    label: 'Allergy Block',
    color: 'text-red-800',
    bg: 'bg-red-100',
    border: 'border-red-400',
    icon: '⊘',
    dotColor: 'bg-red-700',
  },
  blocked_interaction: {
    label: 'Interaction Block',
    color: 'text-red-800',
    bg: 'bg-red-100',
    border: 'border-red-400',
    icon: '⊘',
    dotColor: 'bg-red-700',
  },
  seek_professional_review: {
    label: 'Consult a Professional',
    color: 'text-purple-700',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    icon: '⚕',
    dotColor: 'bg-purple-500',
  },
} as const;

export type ClassificationType = keyof typeof CLASSIFICATION_CONFIG;
