"""Initial Phase 6 schema

Revision ID: 1efabd3beb36
Revises: 
Create Date: 2026-08-20 22:32:05.863307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efabd3beb36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('allergen_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('allergen_family', sa.String(), nullable=True),
    sa.Column('cross_reactive_with', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('allergen_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conditions',
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('icd10_code', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('key_nutrients', sa.JSON(), nullable=True),
    sa.Column('relevant_parameters', sa.JSON(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('condition_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('publication', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('accessed_date', sa.Date(), nullable=True),
    sa.Column('version_or_edition', sa.String(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('foods',
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('cuisine_origin', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('preparation_notes', sa.String(), nullable=True),
    sa.Column('is_raw', sa.Boolean(), nullable=True),
    sa.Column('cooking_methods', sa.JSON(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.Column('is_jain', sa.Boolean(), nullable=True),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=True),
    sa.Column('is_lactose_free', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_food_id', sa.String(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('medications',
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=False),
    sa.Column('brand_names', sa.JSON(), nullable=True),
    sa.Column('drug_class', sa.String(), nullable=False),
    sa.Column('drug_subclass', sa.String(), nullable=True),
    sa.Column('indications', sa.JSON(), nullable=True),
    sa.Column('dosage_forms', sa.JSON(), nullable=True),
    sa.Column('route', sa.JSON(), nullable=True),
    sa.Column('standard_timing', sa.String(), nullable=True),
    sa.Column('timing_category', sa.String(), nullable=True),
    sa.Column('half_life_hours', sa.Numeric(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('black_box_warning', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('regulatory_label_date', sa.Date(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=True),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_table('nutrients',
    sa.Column('nutrient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nutrient_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition_nutrition_rules',
    sa.Column('cn_rule_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('nutrient_id', sa.UUID(), nullable=True),
    sa.Column('food_category', sa.String(), nullable=True),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(), nullable=True),
    sa.Column('threshold_unit', sa.String(), nullable=True),
    sa.Column('is_conditional', sa.Boolean(), nullable=True),
    sa.Column('condition_parameter', sa.String(), nullable=True),
    sa.Column('condition_operator', sa.String(), nullable=True),
    sa.Column('condition_value', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('rule_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.nutrient_id'], ),
    sa.PrimaryKeyConstraint('cn_rule_id')
    )
    op.create_table('drug_food_interactions',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('nutrient_id', sa.UUID(), nullable=True),
    sa.Column('food_category', sa.String(), nullable=True),
    sa.Column('food_component', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('mechanism', sa.String(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('timing_window', sa.String(), nullable=True),
    sa.Column('quantity_threshold', sa.String(), nullable=True),
    sa.Column('is_conditional', sa.Boolean(), nullable=True),
    sa.Column('condition_id', sa.UUID(), nullable=True),
    sa.Column('condition_parameter', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.medication_id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.nutrient_id'], ),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_table('drug_nutrient_depletions',
    sa.Column('depletion_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('nutrient_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('mechanism', sa.String(), nullable=True),
    sa.Column('clinical_significance', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.medication_id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.nutrient_id'], ),
    sa.PrimaryKeyConstraint('depletion_id')
    )
    op.create_table('evidence',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('evidence_summary', sa.String(), nullable=False),
    sa.Column('relevant_quote', sa.String(), nullable=True),
    sa.Column('page_or_section', sa.String(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('food_allergens',
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('allergen_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_trace', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergies.allergen_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'allergen_id')
    )
    op.create_table('food_nutrition',
    sa.Column('food_nutrition_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('nutrient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('per_quantity', sa.Numeric(), nullable=True),
    sa.Column('per_unit', sa.String(), nullable=True),
    sa.Column('preparation_state', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.nutrient_id'], ),
    sa.PrimaryKeyConstraint('food_nutrition_id')
    )
    op.create_table('food_serving_sizes',
    sa.Column('serving_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount_g', sa.Numeric(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.PrimaryKeyConstraint('serving_id')
    )
    op.create_table('rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_rule_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('evidence_level', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecation_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['rules.rule_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('user_allergies',
    sa.Column('user_allergy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('allergen_id', sa.UUID(), nullable=True),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergies.allergen_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_allergy_id')
    )
    op.create_table('user_conditions',
    sa.Column('user_condition_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('diagnosed', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('disease_stage', sa.String(), nullable=True),
    sa.Column('lab_values', sa.JSON(), nullable=True),
    sa.Column('treatment_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_condition_id')
    )
    op.create_table('user_medications',
    sa.Column('user_medication_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('dose_amount', sa.Numeric(), nullable=True),
    sa.Column('dose_unit', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('timing_instructions', sa.String(), nullable=True),
    sa.Column('timing_relative_to_meal', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.medication_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_medication_id')
    )
    op.create_table('user_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('dietary_pattern', sa.String(), nullable=True),
    sa.Column('nutritional_goals', sa.JSON(), nullable=True),
    sa.Column('cuisine_preferences', sa.JSON(), nullable=True),
    sa.Column('food_preferences', sa.JSON(), nullable=True),
    sa.Column('cooking_time_max_minutes', sa.Integer(), nullable=True),
    sa.Column('budget_level', sa.String(), nullable=True),
    sa.Column('lifestyle_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('rule_evaluations',
    sa.Column('eval_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('eval_id')
    )
    op.create_table('rule_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('cn_rule_id', sa.UUID(), nullable=True),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cn_rule_id'], ['condition_nutrition_rules.cn_rule_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['drug_food_interactions.interaction_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_targets',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('nutrient_id', sa.UUID(), nullable=True),
    sa.Column('food_category', sa.String(), nullable=True),
    sa.Column('food_component', sa.String(), nullable=True),
    sa.Column('quantity_modifier', sa.String(), nullable=True),
    sa.Column('threshold_amount', sa.Numeric(), nullable=True),
    sa.Column('threshold_unit', sa.String(), nullable=True),
    sa.Column('additional_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.food_id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.nutrient_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('rule_triggers',
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('trigger_group', sa.Integer(), nullable=False),
    sa.Column('trigger_seq', sa.Integer(), nullable=False),
    sa.Column('trigger_on', sa.String(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=True),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('drug_class', sa.String(), nullable=True),
    sa.Column('allergen_id', sa.UUID(), nullable=True),
    sa.Column('dietary_pattern', sa.String(), nullable=True),
    sa.Column('parameter_name', sa.String(), nullable=True),
    sa.Column('parameter_operator', sa.String(), nullable=True),
    sa.Column('parameter_value', sa.String(), nullable=True),
    sa.Column('is_negation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergies.allergen_id'], ),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.medication_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_triggers')
    op.drop_table('rule_targets')
    op.drop_table('rule_evidence')
    op.drop_table('rule_evaluations')
    op.drop_table('user_profiles')
    op.drop_table('user_medications')
    op.drop_table('user_conditions')
    op.drop_table('user_allergies')
    op.drop_table('rules')
    op.drop_table('food_serving_sizes')
    op.drop_table('food_nutrition')
    op.drop_table('food_allergens')
    op.drop_table('evidence')
    op.drop_table('drug_nutrient_depletions')
    op.drop_table('drug_food_interactions')
    op.drop_table('condition_nutrition_rules')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('nutrients')
    op.drop_table('medications')
    op.drop_table('foods')
    op.drop_table('data_sources')
    op.drop_table('conditions')
    op.drop_table('allergies')
    # ### end Alembic commands ###
